### ISSUE TITLE
Traps not working (snmptrapd + SNMPTT)

### ISSUE THREAD

**Issue by carlosarmentac** [zabbix/zabbix-community-docker#105] opened 2018-02-01 18:45 UTC
### Description

dockbix traps config is not working because a exception with SNMPTT

018-02-01 11:00:35,190 DEBG 'snmptrapd' stdout output:
********** SNMPTT v1.4beta2 started: Thu Feb  1 11:00:35 2018 **********
Could not load the Perl module SNMP!  If net_snmp_perl_enable is
enabled then the SNMP module is required.  Please see snmptt.html
for system requirements.  Note:  SNMPTT uses the Net-SNMP package's
SNMP module, NOT the CPAN Net::SNMP module!

2018-02-01 11:00:35,367 DEBG 'snmptrapd' stderr output:
Can't locate SNMP.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at (eval 12) line 1.
died at /usr/sbin/snmptt line 426.

### Steps to Reproduce

1. Install
docker run \
    -d \
    --name dockbix \
    -p 8888:80 \
    -p 10055:10088 \
    -v /etc/localtime:/etc/localtime:ro \
    --link dockbix-db:dockbix.db \
    --env="ZS_DBHost=dockbix.db" \
    --env="ZS_DBUser=zabbix" \
    --env="ZS_DBPassword=my_password" \
    --env="XXL_zapix=true" \
    --env="ZS_CacheSize=1024M" \
    --env="XXL_grapher=true" \
    --env="SNMPTRAP_enabled=true" \
    monitoringartist/dockbix-xxl:latest

**Expected behavior:** Traps working

**Actual behavior:** Traps can not be catched by zabbix server

**Reproduces how often:** 100%

### Versions

Containers: 13
 Running: 8
 Paused: 2
 Stopped: 3
Images: 13
Server Version: 18.01.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog

Linux xxxxxxx 4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### You Docker knowledge level

Begginer

**Comment by jangaraj** [comment] 2018-02-01 18:49
Hi Carlos,

I'm closing this one because it's duplicate of https://github.com/monitoringartist/dockbix-xxl/issues/99. I'm happy to review any PR, which will fix it.

**Closed as completed by jangaraj** 2018-02-01 18:49 UTC
Labels: duplicate
